version: "3.8"
services:
    vue:
        build: .
        ports: 
            - "8080:8080"
        volumes:
            - "./app/:/app"
            # Link local directory and workdir
            - "/app/node_modules" 
