version: "3.8"
services:
    vue:
        build: .
        ports: 
            - "8080:8080"
        volumes:
            - "/app/node_modules" 
            # Link the local folder to the workdir 
            - "./app/:/app"